---

- import_tasks: pre-reqs.yml

# - import_tasks: start_stop_instances.yml
  # when: (operation == "running") or
        # (operation == "stopped")
#
# - import_tasks: remove_infra.yml
  # when:
    # - operation == "absent"
#
# - import_tasks: remove_vpc.yml
  # when:
    # - operation == "absent"
    # - delete_vpc

- import_tasks: process-cf-template.yml

- import_tasks: manage-cf-stack.yml
