---
- name: Ensure the underlaying infrastructure is {{ action }}
  cloudformation:
    stack_name: "{{ env_id }}"
    state: "{{ action }}"
    region: "{{ aws_region }}"
    template: "{{ cftemplate.dest }}"
    template_parameters:
      VPCCIDR: "{{ VPCCIDR }}"
      PrivateSubnet1CIDR: "{{ PrivateSubnet1CIDR }}"
      PrivateSubnet2CIDR: "{{ PrivateSubnet2CIDR }}"
      PrivateSubnet3CIDR: "{{ PrivateSubnet3CIDR }}"
      Image: "{{ aws_image_name }}"
      KeyPairName: "{{ aws_key_name }}"
      MasterInstanceType: "{{ master_flavor }}"
      EtcdInstanceType: "{{ etcd_flavor }}"
      NodesInstanceType: "{{ app_node_flavor }}"
      InfraInstanceType: "{{ infra_node_flavor }}"
      CNSInstanceType: "{{ cns_node_flavor }}"
      MasterHealthTarget: "TCP:{{ openshift_master_api_port }}"
