---

#delete_vpc: false

default_root_volume: '/dev/sda1'
default_docker_volume: '/dev/xvdb'
default_cns_volume: '/dev/xvdg'

default_root_volume_size: '50'
default_docker_volume_size: '40'
default_cns_volume_size: '200'
