---

- name: "Create/Apply OpenShift Cluster '{{ entry.object }}' - based on individual files"
  include: create-one-entry.yml
  with_items:
  - "{{ entry.content | default([]) }}"
  when: 
  - item.file is defined 
  - item.file|trim != ''

- name: "Create/Apply OpenShift Cluster '{{ entry.object }}' - based on directory"
  command: >
    oc {{ action }} -f {{ tmp_inv_dir }}{{ entry.content_dir }}
  when:
  - entry.content_dir is defined 
  - entry.content_dir|trim != ''
