---

- name: "Copy inventory content to remote host(s) if not running 'locally'"
  include: copy-inventory-to-remote.yml
  when:
  - ansible_connection != 'local'

- name: "Create OpenShift objects"
  include: process-content.yml
  with_items:
  - "{{ openshift_cluster_content | default([]) }}"
  loop_control:
    loop_var: entry
  when:
  - entry.content is defined or entry.content_dir is defined 
