---

- name: "Create OpenShift objects for '{{ entry.object }}' with params"
  include: process-one-entry.yml
  with_items:
  - "{{ entry.content }}"
  when:
  - item.template is defined 
  - item.template != ''
  - item.params is defined
  - item.params != ''
